---
title: "每週一圖作業資料檔"
output: html_document
params:
  組員: ["王先誠"]  
  學號: ["410574226"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}
information <- data.frame(
  學年度=c(99,100,101,102,103,104,106,107,109),
  身高=c(154,160,172,173,175,176,177,177,177),
  體重=c(43,48,58,56,62,63,62,65,65),
  立定跳遠=c(180,165,239,235,235,240,240,240,250)
  
)
graphData<- 
  select(information,"學年度","身高","體重","立定跳遠")
save(graphData,file = "graphData.Rda")
# save(<所有在graph_story.Rmd要用的物件列出來，中間用逗號分隔>, file="graphData.Rda") # 此行放在最後一行
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
