title: "每週一圖作業繪圖說明檔"
output: html_document
params:
  組員: ["王先誠"]  
  學號: ["410574226"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```


#### 繪圖程式

```{r graph, echo=T, eval=T}
# load("graphData.Rda") # 此行為第一行
load("graphData.Rda")

colorspace::sequential_hcl(n = 7, h = 135, c = c(45, NA, NA), l = c(35, 95), power = 1.3, register = "Custom-Palette")

graphData  %>%
  ggplot(aes(x=graphData$學年度))+
  geom_point(aes(y=graphData$身高),
             shape =18,
             size=6,
             color="red")+
   geom_path(aes(y=graphData$身高))+
  geom_col(aes(y=graphData$立定跳遠,      fill=(graphData$體重)),alpha=0.7)+
  scale_x_continuous(breaks = graphData$學年度,
                     labels=graphData$學年度)+
  labs(title="我的歷年身高、體重、立定跳遠距離", x="學年度", y="身高/立定跳遠距離(cm)",fill="體重(kg)")+
  theme(
    axis.text.x = element_text
    (face="bold", color = "black", size=10),
    axis.text.y = element_text
    (face = "bold",color="black", size=10))+
  geom_text(x=99,y=10,label="國一",size=5)+
  geom_text(x=100,y=10,label="國二",size=5)+
  geom_text(x=101,y=10,label="國三",size=5)+
  geom_text(x=102,y=10,label="高一",size=5)+
  geom_text(x=103,y=10,label="高二",size=5)+
  geom_text(x=104,y=10,label="高三",size=5)+
  geom_text(x=106,y=10,label="大二",size=5)+
  geom_text(x=107,y=10,label="大三",size=5)+
  geom_text(x=109,y=10,label="明年",size=5)+
  geom_text(x=109,y=150,label=177,size=5)+
  geom_text(x=109,y=240,label=260,size=5)+
    scale_fill_continuous_sequential(
    palette="Custom-Palette")

```

#### 設計說明
說明想傳達的訊息（必要）及設計想法（非必要）。寫在***下一行。
*** 
此圖描繪出我的歷年身高、體重、立定跳遠距離，可以看見三者均隨著年齡增長而上升，立定跳遠距離大概在國三之後就維持不變，成高也是相同情況，而體重則是在大學時逐漸穩定在65公斤，明年的立定跳遠目標是260公分。
