---
title: "Untitled"
author: "Steven"
date: "2019年10月9日"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)
font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/graphData_homework2019-10-08_016.Rda?raw=true"))
graphData %>%
  ggplot()+
  geom_tile(
    aes(x=國家,y=職業,fill=人數)
  )
```

## linetype

```{r}
library(readr)
disposableIncome <- read_csv("https://www.dropbox.com/s/z80sbjw94cjex8x/disposableIncome.csv?dl=1",locale = locale(encoding = "UTF-8"), skip = 4)
disposableIncome_gather <- read_csv("https://www.dropbox.com/s/cdw1f10jow4frxb/disposableIncome_gather.csv?dl=1")
```

```{r}
c('X1','平均每戶可支配所得','可支配所得按戶數五等分位組-最低所得組','可支配所得按戶數五等分位組-次低所得組','可支配所得按戶數五等分位組-中間所得組','可支配所得按戶數五等分位組-次高所得組','可支配所得按戶數五等分位組-最高所得組') -> names(disposableIncome)
c('年','平均每戶可支配所得','所得組距','可支配所得') -> names(disposableIncome_gather)
```

```{r}
disposableIncome$X1
disposableIncome$平均每戶可支配所得
disposableIncome$`可支配所得按戶數五等分位組-次低所得組`

disposableIncome %>% write_csv("test.csv")

read_csv("test.csv")-> aa
```


```{r}
disposableIncome %>%
  mutate(
    年=as.integer(X1)
  ) -> disposableIncome
disposableIncome %>%
  ggplot(aes(x=年,y=平均每戶可支配所得))+
  geom_line(linetype="dashed")
```

```{r}
disposableIncome %>%
  ggplot(aes(x=年,y=平均每戶可支配所得))+
  geom_line(linetype="33")
```


```{r}
disposableIncome %>%
  ggplot(aes(x=年,y=平均每戶可支配所得))+
  geom_line(linetype='2451')
```

```{r}
library(magrittr)
disposableIncome_gather$所得組距 %<>%
  factor(levels=c(
    "可支配所得按戶數五等分位組-最低所得組",
    "可支配所得按戶數五等分位組-次低所得組",
    "可支配所得按戶數五等分位組-中間所得組",
    "可支配所得按戶數五等分位組-次高所得組",
    "可支配所得按戶數五等分位組-最高所得組"
  )) 
disposableIncome_gather %>%
  ggplot(aes(x=年,y=可支配所得))+
  geom_line(
    aes(linetype=所得組距,size=所得組距)
  ) +
  scale_linetype_manual(
    values=c("15","24","34","51","71")
  ) +
  scale_size_manual(
    values=c(0.1,0.3,0.3,0.5,0.7)*1.5
  ) -> p_linetype
p_linetype
```

```{r}
disposableIncome %>%
  ggplot(aes(x=年,y=平均每戶可支配所得))+
  geom_line(linetype="33")
```

```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/graphData_homework2019-10-08_014.Rda?raw=true"))
```

```{r}
c('年分','地區','來台旅遊人數(萬)') -> names(graphData$travelerFromAsia)
graphData$travelerFromAsia
```


```{r}
graphData$travelerFromAsia$年分 <- as.numeric(graphData$travelerFromAsia$年分)

graphData$travelerFromAsia %>%
  ggplot(aes(x=`年分`,y=`來台旅遊人數(萬)`,color = 地區, linetype = 地區)) +
  geom_line()
```


```{r}
dataCPI <- read_csv("https://www.dropbox.com/s/ov2bvef5o3apei0/PR0101A2Mc.csv?dl=1")
```

```{r}
## 改變數名稱
dataCPI %>% 
  dplyr::rename(
    年月=X1,
    CPI=原始值
  ) -> dataCPI

# 移除「有NA」的row
dataCPI %>% na.omit() -> dataCPI

## 調整class
dataCPI$年月 %>% str_c("/01") %>% #擴增為YMD表示
  ymd() -> dataCPI$年月

# 改成2003M1為基期,其指數為100
dataCPI %>% filter(年月==ymd("2003-01-01")) %>% 
  select(CPI) -> CPI2003M1

dataCPI %>% 
  mutate(CPI=CPI/CPI2003M1$CPI*100) -> dataCPI2
```

```{r}
dataCPI2 %>% ggplot()+
  geom_line(aes(x=年月,y=CPI)) -> basePlot2
basePlot2
```

```{r}
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA))
```

```{r}
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA))+
  scale_y_continuous(limits=c(80,NA)) 
```

```{r}
disposableIncome_gather %>%
  ggplot(aes(x=年,y=可支配所得))+
  geom_line(
    aes(linetype=所得組距)
  ) +
  scale_linetype_manual(
    values=c("15","24","34","51","71"),
    limits=c(
    "可支配所得按戶數五等分位組-次低所得組",
    "可支配所得按戶數五等分位組-中間所得組",
    "可支配所得按戶數五等分位組-次高所得組")
  )
```

```{r}
breakDates <- c("2003-01-01",
                "2005-01-01","2010-01-01","2015-01-01",
                "2018-01-01")
breakDates %>% ymd() -> breakDates

breakLabels <- c("2003",
                 "2005","2010","2015",
                 "2018")
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = breakLabels)
```

```{r}
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = function(x) year(x)-1911)
```

```{r}
load("C:/Users/steve/Downloads/graphData_homework2019-10-07_001.Rda")
```

```{r}
load("作品展示/graphData_homework2019-10-07_001.Rda")
```

