---
title: "Untitled"
author: "Steven"
date: "2019/11/13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(ggplot2)
library(stringr)
library(dplyr)
```

```{r}
outer <-     
  rbind( # 外圍
    c(1,5),
    c(2,1),
    c(5,1),
    c(5,5),
    c(1,5)) # 必需自行輸入起點close it

hole <-
  rbind( # 洞
    c(2,4),
    c(3,2),
    c(4,3),
    c(2,4))  # 必需自行輸入起點close it
  
poly <- st_polygon(
  list(
    outer, 
    hole
  )
) 

poly %>% ggplot()+geom_sf()
```

```{r}
load(url("https://www.dropbox.com/s/uvco1te2kbs6o01/MRT_Taipei.Rda?dl=1"))
```

```{r}
sf_mrt_tpe %>%
  filter(stringr::str_detect(經過路線,"BL")
         ) ->
  sf_mrt_tpe_bl
```


```{r}
sf_mrt_tpe_bl %>%
  st_coordinates() %>%
  st_linestring() -> sfg_mrt_bl
```

```{r}
sf_mrt_tpe_bl %>%
  mutate(站號=stringr::str_extract(
    經過路線, "(?<=(BL))[:digit:]+")
  ) %>%
  arrange(站號)-> sf_mrt_tpe_bl
sf_mrt_tpe_bl %>%View()
```

```{r}
sf_mrt_tpe_bl %>%
  st_coordinates() %>%
  st_linestring() -> sfg_mrt_bl2
```

```{r}
sfg_mrt_bl2 %>%
  ggplot()+geom_sf()
```

```{r}

```

