---
title: "Untitled"
author: "Steven"
date: "9/18/2019"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)
font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

```{r}
StuList <- list(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuList 
as.data.frame(StuList) -> StuDFfromList
StuDFfromList
```

```{r}
StuDF <- data.frame(
  次序=c(1,2,3,4,5,6,7,8),
  學號=c(172,214,322,425,517,833,752,114),
  姓名=c("小明","大雄","胖虎","小新","大白","阿華","小英","阿美"),
  性別=c("男","男","男","女","女","男","女","男"),
  成績=c(80,42,90,82,50,77,30,90)
  )
StuDF 
```

```{r}
class(StuDF)
typeof(StuDF)
```

```{r}
length(StuDF) # 從向量角度看
nrow(StuDF) # 從矩陣角度看
```

```{r}
library(dplyr)
```

```{r}
str(StuDF)
```

```{r}
head(StuDF)
```

```{r}
StuDF
slice(StuDF,1:3)
slice(StuDF,4:5)
slice(StuDF,n())
```

```{r}
slice(StuDF,(n()-1):n())
```

```{r}
StuDF
slice(StuDF,-5:-7)#在r語言裡5,6,7不見
```

```{r}
slice(StuDF,-(5:7))#另一種寫法
```

```{r}
slice(StuDF,1,4,8)#只要1,4,8
```

```{r}
library(readr)
collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")
```

```{r}
slice(collegeData,1:4,(n()-2):n(),101:110)%>% View
```

```{r}
StuDF
mutate(StuDF,
       調分後成績=成績+10) -> StuDF
transmute(StuDF,
          調分後成績=成績+10)->Stu123
```

```{r}
mutate(collegeData,
       男生=一年級男生+二年級男生+三年級男生+四年級男生)-> collegeData
  
collegeData$女生 <-
  collegeData$一年級女生+collegeData$二年級女生+collegeData$三年級女生+collegeData$四年級女生

collegeData$男女生比<-collegeData$男生/collegeData$女生
```

```{r}
StuDF
summarise(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))

```

```{r}
StuDF
mutate(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))
```

```{r}
mutate(StuDF,
       平均成績=mean(成績),
       最高分=max(成績),
       最低分=min(成績),
       調整後成績=成績+(最高分-最低分)/5)
```

```{r}
StuDF
mutate(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績)) -> StuDF2
```

```{r}
StuDF2
names(StuDF2)
select(StuDF2,
       姓名,學號,成績,調分後成績)
select(StuDF2,
       -次序,-性別,-最高分,-最低分)
```

```{r}
select(StuDF2,
       次序,性別,
       contains("最"))

select(StuDF2,
       -次序,-性別,
       -contains("最"))
```

```{r}
select(collegeData,
       contains("男生"))
```

```{r}
StuDF
# logical vector
logiChoose <- c(
  F,F,F,T,T,F,T,F
)
# 使用logical vector選擇所要觀測值"女"
StuDF[logiChoose,]
```

```{r}
StuDF
filter(StuDF,
       性別=="女")
filter(StuDF,
       (性別=="女" & 成績>60))
filter(StuDF,
       性別=="女",
       成績>60) # 多個AND條件可用,分隔
```

```{r}
collegeData
filter(collegeData,
       縣市名稱=="30臺北市") 
```

```{r}
collegeData
filter(collegeData,
       縣市名稱=="30臺北市"|縣市名稱=="01新北市"
)
```

```{r}
group_by(StuDF,
         性別) -> StuDF_by性別

# 使用grouped data frame
summarise(StuDF_by性別,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))

# 使用ungrouped data frame
summarise(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))
```

```{r}
mutate(
  StuDF_by性別,
  最高分=max(成績),
  最低分=min(成績),
  調分大小=(最高分-最低分)/5,
  調分後成績=成績+調分大小
) -> StuDF_依性別調分
StuDF_依性別調分
```

```{r}
ungroup(StuDF_依性別調分) -> 
  StuDF_調分後
```

```{r}
group_by(collegeData,
         縣市名稱,體系別,等級別)->
  collegeData_grouped

summarise(collegeData_grouped,
          一年級男生總數=sum(一年級男生),
          一年級女生總數=sum(一年級女生),
          學校數目=n())
```

