---
title: "10/23 練習"
author: "Steven"
date: "2019年10月23日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library2014 <- read_csv("https://www.dropbox.com/s/999hy0u1y98y6ep/library2014.csv?dl=1")
graphList <- list()
```

```{r}
library(dplyr)
library2014 %>%
  mutate(
    學院=reorder(學院,學號,length,order=T),
    讀者年級=reorder(讀者年級,讀者年級, order=T)
  ) -> library2014
library(ggplot2)
library2014 %>% 
  ggplot()-> graphList$圖書_ggplotOnly

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院), fill="#5A99B3", width=0.7
    )
```

```{r}
graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院) # 預設 stat="count"
  )
```

```{r}
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院), 
    geom="bar" # geom_bar內訂會取 count來當y
  )
```

```{r}
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院,y=stat(prop),group="全校"), 
    geom="bar" # geom_bar內訂會取 count來當y
  )+
  stat_count(aes(x=學院,y=stat(prop),group="全校",label=round(stat(prop),2)),geom="text")
```

